# Generated by Django 4.2.7 on 2023-11-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_post_posted_commnt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnt',
            new_name='Comment',
        ),
    ]
