# Generated by Django 4.2.10 on 2024-04-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contents',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
